### ISSUE TITLE
Clarification regarding assignment submission

### ISSUE THREAD

**Issue by yashsinghcodes** [GitHub-Octernships/Shuffle-Cybersecurity-Engineer#3]
Hi,
I know I'm bit late, but I wanted to get a clarification over how are we going to submit the assignment as in the readme.md file it is just written that we had to submit the app here. Does that mean making a pull request, how does it exactly work. I joined this octernship bit late but have a working app ready. Can you please help. Thanks

**Comment by satti-hari-krishna-reddy** [comment]
Hi @yashsinghcodes thank you for raising the PR , i was just thinking about to raise one.

**Comment by yashsinghcodes** [comment]
Hi @satti-hari-krishna-reddy, I got the answer you probably gotten a email which is an invite to your private repo, you can push your code to the repo for submission thanks. I'm closing the issue.

**Comment by satti-hari-krishna-reddy** [comment]
Got it , so we need to push the code into assignment 1 branch in our private repo and create a pr to merge into the main branch? Or should we merge directly into the main branch ?

**Comment by yashsinghcodes** [comment]
Nope, I think we just have to push the code into that repo as the owner of the repo is GitHub-Octernship they can view it, So no need of any PR.
